### ISSUE TITLE
Please rename projet to comply with 3rd party naming

### ISSUE THREAD

**Issue by snicoll** [gevoulga/spring-boot-quickfixj#1]
As [referenced in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming), we prefer 3rd party starters not to start with `spring-boot`. Can you please rename the artifacIds? For instance,`quickfixj-spring-boot-*`

**Comment by gevoulga** [comment]
renamed as requested
