### ISSUE TITLE
ConfigurationProperties should not be a `@Configuration`

### ISSUE THREAD

**Issue by snicoll** [gevoulga/spring-boot-quickfixj#2]
A `@ConfigurationProperties` should not have a `@Configuration` stereotype as it does not (and sould not) declare additional beans for the context.

That stereotype is [useless anyway](https://github.com/gevoulga/spring-boot-quickfixj/blob/6191ce59a3b864a4cb12a694d20b127c3add80ae/spring-boot-starter-quickfixj/src/main/java/ch/voulgarakis/spring/boot/starter/quickfixj/autoconfigure/QuickFixJAutoConfiguration.java#L31).

**Comment by gevoulga** [comment]
removed @Configration from QuickfixjBootProperties.
Left @EnableConfigurationProperties on QuickfixJAutoConfiguration
