### ISSUE TITLE
Provide documentation for configuration properties

### ISSUE THREAD

**Issue by snicoll** [gevoulga/spring-boot-quickfixj#3]
While the annotation processor for generating metadata from `@ConfigurationProperties` types is present, no documentation for keys are generated at the moment.

This can be achieved by adding field javadoc, see [the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata-annotation-processor) for more details.

**Comment by gevoulga** [comment]
javadoc added above fields; additiona-spring-configuration-metadata.json also has description
