### ISSUE TITLE
Additional configuration metadata is useless

### ISSUE THREAD

**Issue by snicoll** [gevoulga/spring-boot-quickfixj#5]
The metadata is already generated automatically from the code so [that file](https://github.com/gevoulga/spring-boot-quickfixj/blob/master/quickfixj-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json) seems to be useless as far as I can see.

**Comment by gevoulga** [comment]
quickfixj.startup.timeout property is not specified in the [QuickFixJBootProperties file](https://github.com/gevoulga/spring-boot-quickfixj/blob/master/quickfixj-spring-boot-starter/src/main/java/ch/voulgarakis/spring/boot/starter/quickfixj/autoconfigure/QuickFixJBootProperties.java).
This is the reason the [additional-spring-configuration-metadata](https://github.com/gevoulga/spring-boot-quickfixj/blob/master/quickfixj-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json) is defined.
I don't know how it works though with the existing properties defined in the class.
Are they overriden?

**Comment by snicoll** [comment]
> quickfixj.startup.timeout property is not specified in the QuickFixJBootProperties file.

Sorry I missed that.

> I don't know how it works though with the existing properties defined in the class.

The documentation [answers that question](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata-additional-metadata). `TL;DR` just define the timeout property and remove all the rest.

**Comment by gevoulga** [comment]
done. thx for the comments
